### ISSUE TITLE
Animal Crossing: Population Growing PAL Support

### ISSUE THREAD

**Issue by Levi86** [Cuyler36/ACSE#2]
I used the previous version of ACSE and it went without any trouble, but now, when I tried to open the same file in this new version, it tells me it isn't a valid save file.

**Comment by Cuyler36** [comment]
That means it isn't the correct file size. Can you send me the file or a link to it? All of my .GCI and .GCS files open properly. Also if you could explain what method you used to obtain the file (Dolphin Save dump, GameCube Memory Card dump, etc.)

Edit: The reason it worked fine in the original version is due to how the file was checked. Instead of using known file sizes for each extension and save type, I checked the first four bytes of the save area and made sure they were "GAFE". Since that felt too hacky and unreliable, I changed to a file size check.

**Comment by Levi86** [comment]
Oh, now I see that the pre-release it's only for GC version. I'll be wating for the final release, thanks.

**Comment by Cuyler36** [comment]
Ohhh, which version were you trying to load? Doubutsu no Mori? e+?

**Comment by Levi86** [comment]
I meant the ACSE version, that is a pre-release, well, I'm gonna try again. This version: https://github.com/Cuyler36/ACSE/releases

**Comment by Levi86** [comment]
I tried it again but I keep getting this:

![image](https://user-images.githubusercontent.com/29325000/28002424-b3a26074-64fa-11e7-973e-96c3985b1b75.png)

**Comment by Cuyler36** [comment]
Your issue seems to be you're using the PAL version of Animal Crossing. If you look at the file name, you'll see "GAFP" in it. Currently, only the North American release is supported (GAFE). Would you mind sending me the file? I can try to add support in for it.

Edit:
I see you have discord. If you would like, you can add me on it so I can fix this easier. My user is Cuyler#0602.

**Comment by Levi86** [comment]
ok, thanks, here's the file: 

[01-GAFP-DobutsunomoriP_MURA.zip](https://github.com/Cuyler36/ACSE/files/1134394/01-GAFP-DobutsunomoriP_MURA.zip)

**Comment by Cuyler36** [comment]
Went ahead and pushed an update that adds support. Here's the link: https://github.com/Cuyler36/ACSE/releases/tag/0.1.1

Keep in mind that there are a lot of Acre Images missing. Let me know if you encounter any bugs, and enjoy!
