### ISSUE TITLE
Animal Crossing City Folk Issues?

### ISSUE THREAD

**Issue by tootyta** [Cuyler36/ACSE#41]
So when editing my Animal Crossing City Folk town, I ran into multiple issues with the editor. The first being that my birthday shows as this 
![image](https://user-images.githubusercontent.com/17104414/45931118-a4dabe80-bf2e-11e8-8fbd-02b5fa168ed5.png) . Second, when editing my acres, they show up as this? 
![image](https://user-images.githubusercontent.com/17104414/45931123-bb811580-bf2e-11e8-9580-e4af3bb5cb65.png) I'm not sure if that's supposed to happen. The same happens with my town map. Also, 
![image](https://user-images.githubusercontent.com/17104414/45931137-e9665a00-bf2e-11e8-88fa-2b0a71607747.png) how come I can't edit the Weather/Native Fruit? Finally,  none of my villagers appear in the villagers section, which is blank. I can't change my house size either and my roof color.

**Comment by Cuyler36** [comment]
Some of those features are disabled for various reasons (hence the grayed out bars). Weather & native fruit haven't been researched yet. Same with house size & roof color.

Villagers in City Folk all store their textures and names in the file, and I haven't bothered reverse engineering them yet, which is why it's blank. Before version 1.0.0 releases it'll be done.

As for the acres showing up as unknown that shouldn't happen. Can you attach your save file to a reply here so I can take a look at which acres are wrong?

**Comment by Cuyler36** [comment]
The acres showing up as unknown images should now be fixed. I forgot to finish dumping all the acre map icons.

**Comment by Cuyler36** [comment]
Closing this as most of the issues that were shown are now fixed. If you find any more issues, please report them!
