### ISSUE TITLE
Windows 8 Issue?

### ISSUE THREAD

**Issue by tootyta** [Cuyler36/ACSE#46]
I recently downloaded this program on a Windows 8 PC. Once I launched it, nothing happened (the program didn't appear). I checked task manager and it seems that when I open the program, it only opens for a few seconds, then disappears.

**Comment by Cuyler36** [comment]
Do you have .NET 4.7.2 installed? https://dotnet.microsoft.com/download/dotnet-framework-runtime/net472

**Comment by tootyta** [comment]
Windows 8 does not support .NET 4.7.2, however, I have installed the latest supported version of .NET, which was .NET 4.6.

**Comment by ghost** [comment]
If you are still running Windows 8, I urge you to upgrade to 8.1. You are not receiving important security updates anymore since 2016, and 8.1 is compatible with 4.7.2. It is a free upgrade, as well.

https://support.microsoft.com/en-ca/help/15288/windows-8-update-to-windows-8-1
https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements
